"use client";
import { useEffect,useState } from "react";
import { btn, estadiaApi, EstadiaPersona, Habitacion, input, panel } from "./estadiaApi";
export default function ControlHabitaciones({responsable}:{responsable:string}){
 const [habs,setHabs]=useState<Habitacion[]>([]);const [personas,setPersonas]=useState<EstadiaPersona[]>([]);const [dni,setDni]=useState("");const [hab,setHab]=useState("");const [msg,setMsg]=useState("");
 const cargar=async()=>{try{const [a,b]=await Promise.all([estadiaApi<Habitacion[]>("estadiaListarHabitaciones"),estadiaApi<EstadiaPersona[]>("estadiaListarPresentes")]);setHabs(a);setPersonas(b)}catch(e){setMsg(e instanceof Error?e.message:"Error")}};
 useEffect(()=>{void cargar()},[]);
 async function asignar(){const p=personas.find(x=>`${x.idIngreso}|${x.dni}`===dni);if(!p||!hab)return setMsg("Selecciona persona y habitación.");try{await estadiaApi("estadiaAsignarHabitacion",{idIngreso:p.idIngreso,dni:p.dni,nombre:p.nombre,placa:p.placa,proveedor:p.proveedor,habitacion:hab,responsable});setMsg("Habitación asignada.");await cargar()}catch(e){setMsg(e instanceof Error?e.message:"Error")}}
 async function limpiar(numero:string){try{await estadiaApi("estadiaConfirmarLimpieza",{habitacion:numero,responsable});await cargar()}catch(e){setMsg(e instanceof Error?e.message:"Error")}}
 const counts=(s:string)=>habs.filter(h=>h.estado===s).length;
 return <section style={{display:"grid",gap:16}}><h1>Control de Habitaciones</h1><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>{["DISPONIBLE","OCUPADA","RESERVADA","POR LIMPIAR","FUERA DE SERVICIO"].map(s=><div style={panel} key={s}><small>{s}</small><strong style={{display:"block",fontSize:26}}>{counts(s)}</strong></div>)}</div>
 <div style={{...panel,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,alignItems:"end"}}><label>Huésped<select style={input} value={dni} onChange={e=>setDni(e.target.value)}><option value="">Seleccionar...</option>{personas.filter(p=>!p.habitacion).map(p=><option key={`${p.idIngreso}-${p.dni}`} value={`${p.idIngreso}|${p.dni}`}>{p.nombre} · {p.placa}</option>)}</select></label><label>Habitación disponible<select style={input} value={hab} onChange={e=>setHab(e.target.value)}><option value="">Seleccionar...</option>{habs.filter(h=>h.estado==="DISPONIBLE").map(h=><option key={h.numero}>{h.numero}</option>)}</select></label><button style={btn} onClick={()=>void asignar()}>Asignar habitación + kit</button></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}>{habs.map(h=><div style={panel} key={h.numero}><strong>Habitación {h.numero}</strong><div style={{margin:"7px 0",fontWeight:800}}>{h.estado}</div>{h.huesped&&<small>{h.huesped}<br/>{h.placa}</small>}{h.estado==="POR LIMPIAR"&&<button style={{...btn,width:"100%",marginTop:10}} onClick={()=>void limpiar(h.numero)}>Confirmar limpieza</button>}</div>)}</div>{msg&&<div style={panel}>{msg}</div>}</section>
}
