"use client";
import type {CSSProperties} from "react";
export type EstadiaPersona={idIngreso:string;dni:string;nombre:string;rol:string;placa:string;proveedor:string;fechaIngreso:string;salidaPrevista?:string;fechaSalida?:string;habitacion?:string;estado:"PRESENTE"|"SALIO";guardia?:string;turno?:string};
export type Habitacion={numero:string;estado:"DISPONIBLE"|"OCUPADA"|"RESERVADA"|"POR LIMPIAR"|"FUERA DE SERVICIO";dni?:string;huesped?:string;placa?:string;proveedor?:string;fechaIngreso?:string;salidaPrevista?:string;observacion?:string;responsable?:string};
export async function estadiaApi<T>(action:string,payload:Record<string,unknown>={}):Promise<T>{const r=await fetch("/api/sheets",{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify({action,payload})});const j=await r.json().catch(()=>({ok:false,error:"Respuesta inválida del servidor."}));if(!r.ok||!j.ok)throw new Error(j.error||"No se pudo completar la operación.");return j.data as T}
export function duracionDesde(v?:string,h?:string){if(!v)return"-";const a=new Date(v).getTime(),b=h?new Date(h).getTime():Date.now();if(!Number.isFinite(a)||!Number.isFinite(b)||b<a)return"-";const m=Math.floor((b-a)/60000),d=Math.floor(m/1440),hh=Math.floor((m%1440)/60),mm=m%60;return`${d?`${d}d `:""}${hh}h ${mm}m`}
export function fechaHora(v?:string){if(!v)return"-";const d=new Date(v);if(isNaN(d.getTime()))return String(v);return `${d.toLocaleTimeString("es-PE",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"})}   ${d.toLocaleDateString("es-PE",{day:"2-digit",month:"2-digit",year:"numeric"})}`}
export const panel:CSSProperties={background:"#fff",border:"1px solid #dce6e4",borderRadius:14,padding:18,boxShadow:"0 3px 12px rgba(0,0,0,.05)"};
export const btn:CSSProperties={border:0,borderRadius:9,padding:"10px 14px",fontWeight:800,cursor:"pointer",background:"#174d47",color:"#fff"};
export const input:CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #cbd8d5",borderRadius:8,padding:"9px 10px",background:"#fff"};
export const kpi=(bg:string,border:string):CSSProperties=>({...panel,background:bg,borderColor:border});
export const page:CSSProperties={display:"grid",gap:18,padding:"8px 24px 28px",maxWidth:1600,margin:"0 auto"};
export const roomStyle:Record<string,CSSProperties>={DISPONIBLE:{background:"#eaf8ef",border:"2px solid #55b875"},OCUPADA:{background:"#fff0ef",border:"2px solid #ef716b"},RESERVADA:{background:"#edf5ff",border:"2px solid #5d9fe8"},"POR LIMPIAR":{background:"#fff7e3",border:"2px solid #e9a72e"},"FUERA DE SERVICIO":{background:"#eef1f3",border:"2px solid #7c8790"}};
export function Loader({text}:{text:string}){return <div style={{position:"fixed",inset:0,zIndex:9999,background:"rgba(8,31,36,.42)",display:"grid",placeItems:"center"}}><div style={{...panel,minWidth:300,textAlign:"center"}}><div style={{fontSize:34}}>⏳</div><b>{text}</b><div style={{fontSize:12,color:"#60706d",marginTop:6}}>Por favor, espera. No cierres esta ventana.</div></div></div>}
