"use client";
import {useEffect,useMemo,useState} from "react";
import {btn,duracionDesde,estadiaApi,EstadiaPersona,fechaHora,input,kpi,Loader,page,panel} from "./estadiaApi";
type Comida="DESAYUNO"|"ALMUERZO"|"CENA"; type Estado={solicitados:number;entregados:number;pendientes:number;retiro:number;reasignados:number};
type EstadoSrv={personas:Record<string,Record<string,any>>;resumen:Record<Comida,Estado>;consumos:{AGUA:number;GASEOSA:number;GALLETAS:number}};
const COMIDAS:Comida[]=["DESAYUNO","ALMUERZO","CENA"];
const vacio=():EstadoSrv=>({personas:{},resumen:{DESAYUNO:{solicitados:0,entregados:0,pendientes:0,retiro:0,reasignados:0},ALMUERZO:{solicitados:0,entregados:0,pendientes:0,retiro:0,reasignados:0},CENA:{solicitados:0,entregados:0,pendientes:0,retiro:0,reasignados:0}},consumos:{AGUA:0,GASEOSA:0,GALLETAS:0}});
export default function EstadiaServicios({responsable}:{responsable:string}){
 const[p,setP]=useState<EstadiaPersona[]>([]),[estado,setEstado]=useState<EstadoSrv>(vacio()),[q,setQ]=useState(""),[sel,setSel]=useState<string[]>([]),[sol,setSol]=useState<Record<Comida,boolean>>({DESAYUNO:false,ALMUERZO:false,CENA:false}),[ent,setEnt]=useState<Record<Comida,boolean>>({DESAYUNO:false,ALMUERZO:false,CENA:false}),[agua,setAgua]=useState(0),[gaseosa,setGaseosa]=useState(0),[galletas,setGalletas]=useState(1),[salida,setSalida]=useState(""),[msg,setMsg]=useState(""),[load,setLoad]=useState("");
 const key=(x:EstadiaPersona)=>`${x.idIngreso}|${x.dni}`;
 const cargar=async()=>{setLoad("Cargando información...");try{const[a,b]=await Promise.all([estadiaApi<EstadiaPersona[]>("estadiaListarPresentes"),estadiaApi<EstadoSrv>("estadiaEstadoServicios")]);setP(a);setEstado(b)}catch(e){setMsg(e instanceof Error?e.message:"Error")}finally{setLoad("")}};
 useEffect(()=>{void cargar()},[]);
 const vis=useMemo(()=>{const z=q.toLowerCase().trim();return !z?p:p.filter(x=>[x.dni,x.nombre,x.placa,x.idIngreso].some(v=>String(v||"").toLowerCase().includes(z)))},[q,p]);
 const eleg=p.filter(x=>sel.includes(key(x)));
 const reset=()=>{setSel([]);setSol({DESAYUNO:false,ALMUERZO:false,CENA:false});setEnt({DESAYUNO:false,ALMUERZO:false,CENA:false});setAgua(0);setGaseosa(0);setGalletas(1)};
 async function guardar(modo:"SOLICITUD"|"ENTREGA",servicios:{servicio:string,cantidad:number}[]){if(!eleg.length)return setMsg("Selecciona al menos una persona.");if(!servicios.length)return setMsg("Selecciona al menos una opción.");setLoad(modo==="SOLICITUD"?"Registrando requerimiento...":"Registrando entrega...");try{await estadiaApi("estadiaRegistrarServiciosLote",{personas:eleg,servicios,responsable,modo});reset();await cargar();setMsg(modo==="SOLICITUD"?"✓ Requerimiento registrado.":"✓ Entrega registrada.")}catch(e){setMsg(e instanceof Error?e.message:"Error")}finally{setLoad("")}}
 async function prevista(){if(eleg.length!==1||!salida)return setMsg("Selecciona una sola persona y fecha/hora.");setLoad("Actualizando salida prevista...");try{await estadiaApi("estadiaActualizarSalidaPrevista",{idIngreso:eleg[0].idIngreso,dni:eleg[0].dni,salidaPrevista:salida,responsable});setSalida("");setSel([]);await cargar();setMsg("✓ Salida prevista actualizada.")}catch(e){setMsg(e instanceof Error?e.message:"Error")}finally{setLoad("")}}
 const icono=(x:EstadiaPersona,c:Comida)=>{const v=estado.personas[key(x)]?.[c];return v==="ENTREGADO"?"✓":v==="PENDIENTE"?"⏳":v==="RETIRO"?"✕":v==="REASIGNADO"?"↗":"—"};
 const card=(c:Comida,ico:string,bg:string,bd:string)=>{const z=estado.resumen[c];return <div style={kpi(bg,bd)}><div style={{display:"flex",gap:8,alignItems:"center"}}><span style={{fontSize:25}}>{ico}</span><b>{c[0]+c.slice(1).toLowerCase()}</b></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:4,marginTop:8,fontSize:12}}><span>Solicitados <b>{z.solicitados}</b></span><span>Entregados <b>{z.entregados}</b></span><span>Pendientes <b style={{color:"#c43b34"}}>{z.pendientes}</b></span><span>Retiro/Reasig. <b>{z.retiro+z.reasignados}</b></span></div></div>};
 return <section style={page}>{load&&<Loader text={load}/>}<div><h1 style={{margin:0}}>Estadía, Servicios y Consumos</h1><p>Solicita alimentación, registra la entrega real y controla consumos por persona.</p></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(205px,1fr))",gap:12}}><div style={kpi("#e8f5ff","#83c5ee")}><span style={{fontSize:25}}>👥</span><small style={{display:"block"}}>Personas presentes</small><strong style={{fontSize:31}}>{p.length}</strong></div>{card("DESAYUNO","☕","#fff7d9","#efc84a")}{card("ALMUERZO","🍽️","#fff0df","#f2a24d")}{card("CENA","🌙","#f0ecff","#9a84e8")}<div style={kpi("#eaf6ff","#67a9d4")}><b>🥤 Atención de ingreso</b><div style={{fontSize:12,marginTop:8}}>💧 Agua <b>{estado.consumos.AGUA}</b> · 🥤 Gaseosa <b>{estado.consumos.GASEOSA}</b> · 🍪 Galletas <b>{estado.consumos.GALLETAS}</b></div></div></div>
 <div style={panel}><input style={input} placeholder="Buscar DNI, nombre, placa o ID..." value={q} onChange={e=>setQ(e.target.value)}/><div style={{display:"flex",gap:10,alignItems:"center",marginTop:10}}><label><input type="checkbox" checked={vis.length>0&&vis.every(x=>sel.includes(key(x)))} onChange={e=>setSel(e.target.checked?Array.from(new Set([...sel,...vis.map(key)])):sel.filter(k=>!vis.some(x=>key(x)===k)))}/> Seleccionar todo lo visible</label><b>{sel.length} seleccionada(s)</b></div><div style={{overflowX:"auto",maxHeight:410,marginTop:10}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["","Placa","Persona","DNI","Ingreso","Salida prevista","Permanencia","Hab.","Servicios"].map(x=><th key={x} style={{textAlign:"left",padding:9,borderBottom:"1px solid #ddd"}}>{x}</th>)}</tr></thead><tbody>{vis.map(x=><tr key={key(x)}><td style={{padding:8}}><input type="checkbox" checked={sel.includes(key(x))} onChange={e=>setSel(v=>e.target.checked?[...v,key(x)]:v.filter(k=>k!==key(x)))}/></td><td>{x.placa||"-"}</td><td><b>{x.nombre}</b></td><td>{x.dni}</td><td style={{whiteSpace:"nowrap"}}>{fechaHora(x.fechaIngreso)}</td><td style={{whiteSpace:"nowrap"}}>{fechaHora(x.salidaPrevista)}</td><td>{duracionDesde(x.fechaIngreso)}</td><td>{x.habitacion||"-"}</td><td style={{whiteSpace:"nowrap"}}>D {icono(x,"DESAYUNO")} · A {icono(x,"ALMUERZO")} · C {icono(x,"CENA")}<br/><small>💧{estado.personas[key(x)]?.AGUA||0} 🥤{estado.personas[key(x)]?.GASEOSA||0} 🍪{estado.personas[key(x)]?.GALLETAS||0}</small></td></tr>)}</tbody></table></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14}}><div style={{...panel,background:"#fff9e8"}}><h3>1. Registrar requerimiento de alimentación</h3><p style={{fontSize:13}}>Marca lo que fue solicitado para las personas seleccionadas.</p>{COMIDAS.map(c=><label key={c} style={{display:"block",padding:6}}><input type="checkbox" checked={sol[c]} onChange={e=>setSol(v=>({...v,[c]:e.target.checked}))}/> {c}</label>)}<button style={{...btn,marginTop:8}} onClick={()=>void guardar("SOLICITUD",COMIDAS.filter(c=>sol[c]).map(c=>({servicio:c,cantidad:1})))}>Registrar requerimiento</button></div>
 <div style={{...panel,background:"#edf8f0"}}><h3>2. Registrar entrega de alimentación</h3><p style={{fontSize:13}}>Marca solo la comida que realmente recibió cada persona.</p>{COMIDAS.map(c=><label key={c} style={{display:"block",padding:6}}><input type="checkbox" checked={ent[c]} onChange={e=>setEnt(v=>({...v,[c]:e.target.checked}))}/> {c}</label>)}<button style={{...btn,marginTop:8}} onClick={()=>void guardar("ENTREGA",COMIDAS.filter(c=>ent[c]).map(c=>({servicio:c,cantidad:1})))}>Entregar alimentación</button></div>
 <div style={{...panel,background:"#edf7ff"}}><h3>3. Atención de ingreso</h3><p style={{fontSize:13}}>Agua y gaseosa pueden entregarse juntas. Cantidad aplicada a cada persona seleccionada.</p>{[["💧 Agua",agua,setAgua],["🥤 Gaseosa",gaseosa,setGaseosa],["🍪 Galleta",galletas,setGalletas]].map((x:any)=><label key={x[0]} style={{display:"grid",gridTemplateColumns:"1fr 90px",gap:8,alignItems:"center",marginBottom:8}}>{x[0]}<input style={input} type="number" min="0" value={x[1]} onChange={e=>x[2](Math.max(0,+e.target.value||0))}/></label>)}<button style={btn} onClick={()=>void guardar("ENTREGA",[{servicio:"AGUA",cantidad:agua},{servicio:"GASEOSA",cantidad:gaseosa},{servicio:"GALLETAS",cantidad:galletas}].filter(x=>x.cantidad>0))}>Entregar atención de ingreso</button></div></div>
 <div style={panel}><h3>Salida prevista</h3><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><input style={{...input,maxWidth:300}} type="datetime-local" value={salida} onChange={e=>setSalida(e.target.value)}/><button style={btn} onClick={()=>void prevista()}>Guardar salida prevista</button></div></div>{msg&&<div style={panel}>{msg}</div>}</section>;
}
